### ISSUE TITLE
can it do a triangular arbitrage within a centralized exchange

### ISSUE THREAD

**Issue by drgbajavi** [nelso0/barbotine-arbitrage#1]

**Comment by nelso0** [comment]
No, on centralized exchanges, it would triple the fees so the opportunities are very very rare

**Comment by drgbajavi** [comment]
thanks

**Comment by heyafro** [comment]
dont you meant decentralized exchange?

**Comment by drgbajavi** [comment]
> dont you meant decentralized exchange?

No centralised exchange like binance

**Comment by heyafro** [comment]
thats what the bots written for is for okx binance kucoin. but so many people doing arbitrage. it isnt good anymore. it used to be good 5 years ago lol

**Comment by nelso0** [comment]
> thats what the bots written for is for okx binance kucoin. but so many people doing arbitrage. it isnt good anymore. it used to be good 5 years ago lol
> 
> 

Everyone think that, meanwhile we make profits on cex!

**Comment by heyafro** [comment]
> > thats what the bots written for is for okx binance kucoin. but so many people doing arbitrage. it isnt good anymore. it used to be good 5 years ago lol
> 
> Everyone think that, meanwhile we make profits on cex!

haha yeah i ran the bot last night, and it was okay. i had to add a pause for a longer duration on the best-symbol.py for list 1 and list 2. because the api kept banning me for to many hits per second.

**Comment by heyafro** [comment]
thank you for updating the readme and being honest :)
